// Auth actions
export const authConstant = {
  SET_ERRORS: "SET_ERRORS",
  TOGGLE_USER_LOADING: "TOGGLE_USER_LOADING",
  SET_CURRENT_USER: "SET_CURRENT_USER",
};

// Post options
export const postConstant = {
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  GET_POST: "GET_POST",
  TOGGLE_POST_LOADING: "POST_LOADING",
  GET_POSTS: "GET_POSTS",
  RESET_POST: "RESET_POST",
  TOGGLE_POSTS_LOADING: "POSTS_LOADING",
};

// Comment options
export const commentConstant = {
  CREATE_COMMENT: "CREATE_COMMENT",
  UPDATE_COMMENT: "UPDATE_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  GET_COMMENTS: "GET_COMMENTS",
  TOGGLE_COMMENT_LOADING: "TOGGLE_COMMENT_LOADING",
  TOGGLE_COMMENTS_LOADING: "TOGGLE_COMMENTS_LOADING",
  RESET_COMMENT: "RESET_COMMENT",
};
